import { Cormorant, Cormorant_SC } from "next/font/google";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import "react-datepicker/dist/react-datepicker.css";
import "./globals.css";
import "./datepicker-overrides.css";
import MainMenu from "./components/MainMenu";

config.autoAddCss = false; // do NOT add CSS to fontAwesome automatically

const cormorant = Cormorant({
  variable: "--font-cormorant",
  weight: ["300", "400", "600", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
});

const cormorantSC = Cormorant_SC({
  variable: "--font-cormorant-sc",
  weight: ["300", "400", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${cormorant.variable} ${cormorantSC.variable} antialiased`}
      >
        <MainMenu />
        <main className="pt-24">{children}</main>
      </body>
    </html>
  );
}
